prepare for community site
wmo-im/wis2-notification-message pull request #11
Opened 2022-10-03 14:03 UTC by amilan17

Removed or replaces github links; some editorial updates

2022-10-04 16:00 UTC, amilan17 commented
I also recommend changing this sentence from: 

"Alongside the topic hierarchy, a standard notification message format has been defined. Using such a format will allow the entire WIS2 ecosystem: Data publisher, Data User, Global Services to ensure robustness, effectiveness of WIS2 as a unified weather, climate, water data exchange platform."

to: 
"The standard notification message format ensures that the WIS2 ecosystem (data publisher, data user, and global services) is a robust, effective, and unified data exchange platform for weather, climate, and water. "

2022-10-09 16:19 UTC, tomkralidis requested changes

2022-10-09 16:19 UTC, tomkralidis commented on WIS2_Message_Format_README.adoc
> +| Key | Value(s) | Example | Status | Deßscription
Description

2022-10-09 16:20 UTC, tomkralidis commented
In addition to minor change request, +1 to your suggested update @amilan17

2022-10-18 09:28 UTC, amilan17 commented
@tomkralidis I think this is ready to merge to master.

2022-10-18 11:31 UTC, tomkralidis commented
@amilan17 I made a commit to `editorial` branch as follows:

- update the nullable geometry in the schema (https://github.com/wmo-im/wis2-notification-message/commit/c342aa5cb1e2b9bfa630091aa6a5f66f4be0be5b)
- add a geometry example with elevation (https://github.com/wmo-im/wis2-notification-message/commit/e7ad1b9c7343d9b5e194a845edad6aaf537763cd)

Let me know if these make sense then we can merge.  Thanks!

2022-10-18 11:47 UTC, amilan17 commented
@tomkralidis - looks good to me.

2022-10-18 11:51 UTC, tomkralidis approved these changes

2022-10-18 11:51 UTC, merged