125 update with edits sent to lsp for publication
wmo-im/wis2-notification-message pull request #131
Opened 2024-07-30 14:24 UTC by amilan17

This PR will be a one off update of the publication branch that will serve the purpose of showing exactly what was sent to LSP for publication in the WMO library.

2024-07-30 14:46 UTC, amilan17 commented on standard/requirements/core/REQ_data_id.adoc
> +^|A |A WNM `SHALL` provide a `+properties.data_id+` property.
```suggestion
^|A |A WNM SHALL provide a `+properties.data_id+` property.
```

2024-07-30 14:48 UTC, amilan17 commented on standard/requirements/core/REQ_validation.adoc
> +^|B |Each WNM SHALL provide `+id+`, `+type+`, `+geometry+` and `+properties+` properties for GeoJSON compliance. (see <<WMO schemas server>>)
```suggestion
^|B |Each WNM SHALL provide `+id+`, `+type+`, `+geometry+` and `+properties+` properties for GeoJSON compliance.
```

2024-08-05 09:56 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +|**Required** (one of ``conformsTo`` or ``version``)
to discuss

2024-08-05 10:30 UTC, tomkralidis requested changes

2024-08-05 10:30 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> +For recommended data, WNM links may also provide links to resources that implement access control in support of authentication and authorization. In secure data use cases, a user needs to be able to
```suggestion
For recommended data, WNM links may also provide links to resources that implement access control in support of authentication and authorization. In secure data use cases, a user needs to be able to detect access controlled data as part of data discovery and evaluation. The example demonstrates how to express access control using HTTP Basic authentication for a given data access service.
```

2024-08-05 12:54 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +|**Required** (one of ``conformsTo`` or ``version``)
leave in PR branch, but don't include publication doc because it is a FT amendment.

2024-08-05 12:55 UTC, tomkralidis approved these changes

2024-08-05 12:58 UTC, merged